INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  1, 'texto', 'Texto libre (renglón)', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  2, 'radio', 'Radio buttons', 'C' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  3, 'combo', 'Combo (listado)', 'C' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  4, 'list', 'Lista de múltiples respuestas', 'C' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  5, 'check', 'Checks con múltiples opciones', 'C' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  7, 'label', 'Etiqueta Sub-Título', 'E' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  8, 'textarea', 'Texto libre (área)', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES (  9, 'localidad', 'Localidad', 'E' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 10, 'texto_fecha', 'Tipo fecha', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 11, 'texto_numeroentero', 'Número entero', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 12, 'texto_numerodecimal', 'Número decimal', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 13, 'texto_numeroedad', 'Número entre 1 y 100 (edad)', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 14, 'texto_numeroanio', 'Número entre 1000 y 9000 (año)', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 15, 'texto_mail', 'Texto con formato de correo electrónico', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 16, 'fecha_calculo_anios', 'Tipo fecha con cálculo de años', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 17, 'combo_autocompletado', 'Combo (autocompletable)', 'C' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 18, 'localidad_y_cp', 'Localidad y código postal', 'E' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 19, 'combo_dinamico', 'Lista con valores dinámicos', 'C' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 20, 'texto_numerotelefono', 'Número de teléfono con código internacional y regional', 'A' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 21, 'etiqueta_titulo', 'Etiqueta Título', 'E' );
INSERT INTO sge_componente_pregunta ( numero, componente, descripcion, tipo ) VALUES ( 22, 'etiqueta_texto_enriquecido', 'Etiqueta Texto Enriquecido ', 'E' );
