-- ************************************************************************************************
-- EJEMPLO DE TABLA CON DATOS PARA PODER INCLUIR EN EL KOLLA Y REFERENCIAR LUEGO EN UNA ENCUESTA.
-- ************************************************************************************************
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Escuela Universitaria de Teología' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto de Enseñanza Superior del Ejército' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Tecnológico de Buenos Aires' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Aeronáutico' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario CEMIC' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario de Ciencias de la Salud' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario de la Policía Federal Argentina' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Escuela de Medicina del Hospital Italiano' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario ESEADE' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Gastón Dachary' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario ISALUD' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario ISEDET' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Italiano de Rosario' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Nacional del Arte' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Naval' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Abierta Interamericana' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Adventista del Plata' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Argentina de la Empresa' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Argentina John F. Kennedy' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Atlántida Argentina' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Austral' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Autónoma de Entre Ríos' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Blas Pascal' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad CAECE' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica Argentina Santa María de los Buenos Aires' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica de Córdoba' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica de Cuyo' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica de La Plata' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica de Salta' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica de Santa Fe' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Católica de Santiago del Estero' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Champagnat' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Belgrano' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Bologna' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Buenos Aires' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Ciencias Empresariales y Sociales' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Concepción del Uruguay' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Congreso' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Flores' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de la Cuenca del Plata' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de la Marina Mercante' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Mendoza' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Morón' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de Palermo' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad de San Andrés' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del Aconcagua' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del CEMA' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del Centro Educativo Latinoamericano' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del Cine' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del Museo Social Argentino' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del Norte Santo Tomás de Aquino' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad del Salvador' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Empresarial Siglo XXI' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad FASTA' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Favaloro' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Hebrea Argentina Bar Ilan' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Juan Agustín Maza' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Maimónides' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Catamarca' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Córdoba' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Cuyo' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Entre Ríos' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Formosa' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de General San Martín' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de General Sarmiento' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Jujuy' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de La Matanza' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de La Pampa' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de la Patagonia Austral' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de la Patagonia San Juan Bosco' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de La Plata' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de La Rioja' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Lanús' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Lomas de Zamora' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Luján' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Mar del Plata' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Misiones' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Quilmes' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Río Cuarto' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Rosario' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Salta' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de San Juan' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de San Luis' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Santiago del Estero' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Tres de Febrero' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Tucumán' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Villa María' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional del Centro de la Provincia de Buenos Aires' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional del Comahue' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional del Litoral' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional del Nordeste' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional del Sur' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Notarial Argentina' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Tecnológica Nacional' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Torcuato Di Tella' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Facultad Latinoamericana de Ciencias Sociales (FLACSO)' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario IDEA' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario de Salud Mental de la Asociación Psicoanalítica de Bs. As.' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Instituto Universitario Escuela Argentina de Negocios' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Asociación Médica Argentina' );
INSERT INTO sge_institucion ( nombre ) VALUES ( 'Universidad Nacional de Chilecito' );

-- ************************************************************************************************


