SET CONSTRAINTS ALL DEFERRED;
DELETE FROM arau_instituciones;
INSERT INTO arau_instituciones(institucion_araucano, nombre) VALUES
('32', 'Pontificia Universidad Católica Argentina Santa María de los Buenos Aires'),
('33', 'Universidad de Buenos Aires'), 
('34', 'Universidad Nacional de Catamarca'), 
('35', 'Universidad Nacional del Centro de la Provincia de Buenos Aires'), 
('36', 'Universidad Nacional del Comahue'), 
('37', 'Universidad Nacional de Córdoba'), 
('38', 'Universidad Nacional de Cuyo'), 
('39', 'Universidad Nacional de Entre Ríos'), 
('40', 'Universidad Nacional de Jujuy'), 
('41', 'Universidad Nacional de La Pampa'), 
('42', 'Universidad Nacional de la Patagonia San Juan Bosco'), 
('43', 'Universidad Nacional de La Plata'), 
('44', 'Universidad Nacional del Litoral'), 
('45', 'Universidad Nacional de Lomas de Zamora'), 
('46', 'Universidad Nacional de Luján'), 
('47', 'Universidad Nacional de Mar del Plata'), 
('48', 'Universidad Nacional de Misiones'), 
('49', 'Universidad Nacional del Nordeste'), 
('50', 'Universidad Nacional de Río Cuarto'), 
('51', 'Universidad Nacional de Rosario'), 
('52', 'Universidad Nacional de Salta'), 
('53', 'Universidad Nacional de San Juan'), 
('54', 'Universidad Nacional de San Luis'), 
('55', 'Universidad Nacional de Santiago del Estero'), 
('56', 'Universidad Nacional del Sur'), 
('57', 'Universidad Tecnológica Nacional'), 
('58', 'Universidad Nacional de Tucumán'), 
('59', 'Instituto Universitario de la Policía Federal Argentina'), 
('60', 'Instituto Universitario Aeronáutico'), 
('61', 'Universidad Nacional de La Rioja'), 
('62', 'Universidad CAECE'), 
('64', 'Instituto Tecnológico de Buenos Aires'), 
('65', 'Universidad Argentina de la Empresa'), 
('66', 'Universidad Argentina John F. Kennedy'), 
('67', 'Universidad Católica de Córdoba'), 
('68', 'Universidad Católica de Cuyo'), 
('69', 'Universidad Católica de La Plata'), 
('70', 'Universidad Católica de Salta'), 
('71', 'Universidad Católica de Santa Fe'), 
('72', 'Universidad Católica de Santiago del Estero'), 
('73', 'Universidad de Belgrano'), 
('74', 'Universidad de Concepción del Uruguay'), 
('75', 'Universidad de Mendoza'), 
('76', 'Universidad de Morón'), 
('77', 'Universidad del Aconcagua'), 
('78', 'Universidad del Museo Social Argentino'), 
('79', 'Universidad del Norte Santo Tomás de Aquino'), 
('80', 'Universidad del Salvador'), 
('81', 'Universidad de la Marina Mercante'), 
('82', 'Universidad Juan Agustín Maza'), 
('83', 'Universidad Notarial Argentina'), 
('84', 'Universidad Nacional de Quilmes'), 
('85', 'Universidad Nacional de Formosa'), 
('86', 'Universidad Nacional de La Matanza'), 
('87', 'Universidad Nacional de General Sarmiento'), 
('88', 'Universidad Nacional de San Martín'), 
('89', 'Universidad Nacional de la Patagonia Austral'), 
('90', 'Instituto Universitario del Ejército "Mayor Francisco Romero"'), 
('91', 'Instituto Universitario Naval'), 
('92', 'Universidad Adventista del Plata'), 
('93', 'Universidad Austral'), 
('94', 'Universidad Champagnat'), 
('95', 'Universidad de Ciencias Empresariales y Sociales'), 
('96', 'Universidad de Palermo'), 
('97', 'Universidad de San Andrés'), 
('98', 'Universidad Maimónides'), 
('99', 'Universidad Blas Pascal'), 
('100', 'Universidad Torcuato Di Tella'), 
('101', 'Universidad de la Fraternidad de Agrupaciones  Santo Tomás de Aquino'), 
('102', 'Universidad  Favaloro'), 
('103', 'Instituto Universitario de Ciencias de la Salud de la Fundación Barceló'), 
('104', 'Universidad del Centro Educativo Latinoamericano'), 
('105', 'Universidad del Cine'), 
('106', 'Universidad Hebrea Argentina Bar Ilan'), 
('107', 'Universidad Atlántida Argentina'), 
('108', 'Universidad de la Cuenca del Plata'), 
('109', 'Instituto de Altos Estudios Universitarios Fundación Banco Patricios'), 
('110', 'Universidad del CEMA'), 
('111', 'Universidad de Flores'), 
('112', 'Universidad de Congreso'), 
('113', 'Universidad Empresarial Siglo 21'), 
('672', 'Escuela Universitaria de Teología'), 
('697', 'Universidad Nacional de Lanús'), 
('698', 'Universidad Nacional de Tres de Febrero'), 
('699', 'Universidad Nacional de Villa María'), 
('740', 'Universidad Abierta Interamericana'), 
('741', 'Instituto Universitario Nacional del Arte'), 
('922', 'Instituto Universitario CEMIC'), 
('923', 'Universidad Gastón Dachary'), 
('924', 'Instituto Universitario Escuela Superior de Economía y Administración de Empresas'), 
('925', 'Universidad ISALUD'), 
('2113', 'Instituto Universitario Italiano de Rosario'), 
('2114', 'Instituto Universitario Escuela de Medicina del Hospital Italiano'), 
('2115', 'Instituto Universitario ISEDET'), 
('2116', 'Instituto Universitario IDEA'), 
('2117', 'Universidad Autónoma de Entre Ríos'), 
('2157', 'Instituto Universitario de Seguridad Marítima'), 
('2158', 'Universidad Nacional del Noroeste de la Provincia de Buenos Aires'), 
('2159', 'Facultad Latinoamericana de Ciencias Sociales'), 
('2160', 'Universidad Nacional de Chilecito'), 
('2172', 'Universitá Degli Studi di Bologna'), 
('2302', 'Instituto Universitario Escuela Argentina de Negocios'), 
('2355', 'Instituto Universitario de Salud Mental de la Asociación Psicoanalítica de Buenos Aires'), 
('2356', 'Instituto Universitario del Gran Rosario'), 
('2417', 'Universidad de San Pablo - T'), 
('2459', 'Universidad Nacional de Río Negro'), 
('2479', 'Instituto Universitario de Gendarmería Nacional'), 
('2510', 'Universidad Nacional del Chaco Austral'), 
('2523', 'Universidad del Este'), 
('2624', 'Universidad Nacional Arturo Jauretche'), 
('2625', 'Universidad Nacional de Avellaneda'), 
('2626', 'Universidad Nacional de Moreno'), 
('2631', 'Universidad Nacional de Villa Mercedes'), 
('2632', 'Universidad Nacional del Oeste'), 
('2633', 'Universidad Nacional de Tierra del Fuego, Antártida e Islas del Atlántico Sur'), 
('2634', 'Universidad Nacional José C. Paz'), 
('2684', 'Universidad SIGEN'), 
('2745', 'Universidad Popular Madres de Plaza de Mayo'), 
('2851', 'Universidad de San Isidro "Dr. Plácido Marín"'), 
('2852', 'Universidad Católica de las Misiones'), 
('2853', 'Universidad Metropolitana para la Educación y el Trabajo'), 
('2854', 'Instituto Universitario de Ciencias Biomédicas de Córdoba'), 
('2855', 'Instituto Universitario River Plate'), 
('2899', 'Universidad Provincial del Sudoeste'), 
('2900', 'Universidad Pedagógica Nacional'), 
('2901', 'Universidad Salesiana Argentina'), 
('2997', 'Universidad Nacional de Hurlingham'), 
('3022', 'Universidad Provincial de Córdoba'), 
('3074', 'Universidad de la Defensa Nacional'), 
('3098', 'Instituto Universitario Nacional de Derechos Humanos "Madres de Plaza de Mayo"'), 
('3101', 'Universidad Nacional de las Artes'), 
('3123', 'Universidad Nacional de San Antonio de Areco'), 
('3124', 'Universidad Nacional de Rafaela'), 
('3134', 'Universidad Nacional de los Comechingones'), 
('3148', 'Universidad Provincial de Ezeiza'), 
('3153', 'Instituto Universitario Patagónico de las Artes'), 
('3180', 'Universidad Nacional Raúl Scalabrini Ortiz'), 
('3236', 'Universidad Nacional del Alto Uruguay');
SET CONSTRAINTS ALL IMMEDIATE;