INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 1, 'Mujer');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 2, 'Mujer Trans');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 3, 'Lesbiana');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 4, 'Travesti');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 5, 'Transexual');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 6, 'Tránsgenero');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 7, 'Varón');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 8, 'Varón Trans');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES ( 9, 'Gay');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES (10, 'Bisexual');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES (11, 'No binarie');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES (12, 'Género Fluído');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES (13, 'Ninguna de las anteriores. Especifique');
INSERT INTO mdp_identidad_genero (identidad_genero, nombre) VALUES (14, 'Prefiero No Responder');