INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (1, 'Atacama');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (2, 'Avá Guaraní');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (3, 'Aymara');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (4, 'Chané');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (5, 'Charrúa');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (6, 'Chorote');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (7, 'Chulupí');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (8, 'Comechingón');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (9, 'Diaguita');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (10, 'Diaguita-Calchaquí');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (11, 'Guaraní');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (12, 'Huarpe');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (13, 'Kolla');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (14, 'Lule');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (15, 'Lule Vilela');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (16, 'Maimará');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (17, 'Mapuche');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (18, 'Mbyá Guaraní');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (19, 'Mocoví');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (20, 'Ocloya');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (21, 'Omaguaca');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (22, 'Selk''Nam (Ona)');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (23, 'Pampa');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (24, 'Pilagá');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (25, 'Quechua');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (26, 'Querandí');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (27, 'Rankulche');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (28, 'Sanavirón');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (29, 'Tapiete');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (30, 'Tehuelche');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (31, 'Tilián');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (32, 'Toba');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (33, 'Tonocoté');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (34, 'Tupí Guaraní');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (35, 'Vilela');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (36, 'Wichi');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (61, '*Otros');
INSERT INTO mdi_pueblo_originario (pueblo_originario, nombre) VALUES (62, '*Desconoce');
