INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1, 'Estados Unidos', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 2, 'Canadá', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 3, 'Puerto Rico', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 4, 'Republica Dominicana', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 5, 'Jamaica', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 7, 'Rusia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 20, 'Egipto', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 27, 'Sudafrica', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 30, 'Grecia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 31, 'Holanda', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 32, 'Belgica', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 33, 'Francia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 34, 'España', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 36, 'Hungria', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 39, 'Italia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 40, 'Rumania', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 41, 'Suiza', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 43, 'Austria', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 44, 'Reino Unido', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 45, 'Dinarmarca', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 46, 'Suecia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 47, 'Noruega', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 48, 'Polonia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 49, 'Alemania', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 51, 'Peru', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 52, 'Mexico', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 53, 'Cuba', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 54, 'Argentina', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 55, 'Brasil', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 56, 'Chile', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 57, 'Colombia', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 58, 'Venezuela', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 60, 'Malasia', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 61, 'Australia', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 62, 'Indonesia', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 63, 'Filipinas', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 64, 'Nueva Zelanda', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 65, 'Singapur', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 66, 'Tailandia', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 81, 'Japon', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 82, 'Corea del Sur', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 84, 'Vietnam', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 86, 'China', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 90, 'Turquia', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 91, 'India', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 92, 'Pakistán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 93, 'Afganistán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 94, 'Sri Lanka', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 95, 'Myanmar (ex Birmania)', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 98, 'Iran', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 212, 'Marruecos', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 213, 'Argelia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 216, 'Tunez', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 218, 'Libia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 220, 'Gambia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 221, 'Senegal', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 222, 'Mauritania', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 223, 'Malí', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 224, 'Guinea', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 225, 'Costa de Marfil', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 226, 'Burkina Faso', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 227, 'Níger', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 229, 'Benin', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 230, 'Isla Mauricio', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 231, 'Liberia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 232, 'Sierra Leona', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 233, 'Ghana', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 234, 'Nigeria', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 235, 'Chad', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 236, 'República Centro Africana', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 237, 'Camerun', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 238, 'Cabo Verde', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 239, 'Santo Tome y Principe', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 240, 'Guinea Ecuatorial', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 241, 'Gabón', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 242, 'Congo', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 243, 'Zaire', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 244, 'Angola', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 245, 'Guinea-Bissau', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 249, 'Sudan', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 250, 'Ruanda', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 252, 'Somalia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 254, 'Kenya', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 255, 'Tanzania', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 256, 'Uganda', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 257, 'Burundi', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 258, 'Mozambique', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 260, 'Zambia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 261, 'Madagascar', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 262, 'Reunión', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 263, 'Zimbabwe', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 264, 'Namibia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 265, 'Malawi', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 266, 'Lesotho', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 267, 'Botswana', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 268, 'Swazilandia', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 269, 'Comores', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 290, 'Santa Helena', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 291, 'Eritrea', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 351, 'Portugal', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 352, 'Luxemburgo', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 353, 'Irlanda', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 354, 'Islandia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 355, 'Albania', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 356, 'Malta', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 357, 'Chipre', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 358, 'Finlandia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 359, 'Bulgaria', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 370, 'Lituania', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 371, 'Letonia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 372, 'Estonia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 373, 'Moldova', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 374, 'Armenia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 375, 'Bielorrusia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 376, 'Andorra', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 377, 'Monaco', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 378, 'San Marino', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 379, 'Ciudad del Vatanico', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 380, 'Ucrania', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 381, 'Serbia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 385, 'Croacia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 386, 'Eslovenia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 387, 'Bosnia y Herzegovina', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 389, 'Macedonia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 420, 'República Checa', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 421, 'Eslovaquia', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 423, 'Liechtenstein', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 501, 'Belice', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 502, 'Guatemala', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 503, 'El Salvador', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 504, 'Honduras', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 505, 'Nicaragua', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 506, 'Costa Rica', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 507, 'Panama', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 509, 'Haiti', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 591, 'Bolivia', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 592, 'Guyana', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 593, 'Ecuador', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 594, 'Guayana Francesa', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 595, 'Paraguay', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 596, 'Martinica', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 597, 'Surinam', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 598, 'Uruguay', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 599, 'Antillas Holandesas', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 672, 'Isla Norfolk', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 673, 'Brunei', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 674, 'Nauru', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 675, 'Nueva Guinea y Papua', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 676, 'Tonga', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 677, 'Islas Salomon', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 678, 'Vanuatu', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 679, 'Fidji', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 680, 'Palau', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 685, 'Samoa Occidental', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 686, 'Kiribati', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 687, 'Nueva Caledonia', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 688, 'Tuvalu', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 689, 'Polinesia Francesa', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 690, 'Tokelau', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 691, 'Estados Federador de Micronesia', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 692, 'Islas Marshall', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 850, 'Corea del Norte', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 853, 'Macao', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 856, 'Laos', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 880, 'Bangladesh', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 886, 'Taiwan', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 960, 'Maldivas', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 961, 'Líbano', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 962, 'Jordania', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 963, 'Siria', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 964, 'Irak', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 965, 'Kuwait', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 966, 'Arabia Saudita', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 967, 'Yemen R.A.', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 968, 'Omán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 971, 'Emiratos Arabes Unidos', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 972, 'Israel', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 973, 'Bahrein', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 974, 'Qatar', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 975, 'Bhután', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 976, 'Mongolia', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 977, 'Nepal', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 993, 'Turkmenistán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 994, 'Azerbaiyán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 995, 'Georgia', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 998, 'Kirguistán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1242, 'Bahamas', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 9999, 'Africa SIN Definir', 'AF' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 9998, 'America SIN Definir', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 9997, 'Asia SIN Definir', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 9996, 'Europa SIN Definir', 'EU' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 9995, 'Oceania SIN Definir', 'OC' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 868, 'Trinidad y Tobago', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1268, 'Antigua y Barbuda', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1246, 'Barbados', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1767, 'Dominica', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1473, 'Granada', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1869, 'San Cristóbal y Nevis', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1784, 'San Vicente y Granadinas', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 1758, 'Santa Lucía', 'AM' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 992, 'Tadjikistán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 77, 'Kazajstán', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 670, 'Timor Oriental', 'AS' );
INSERT INTO mug_paises (pais, nombre, continente) VALUES ( 382, 'Montenegro', 'EU' );

