INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 198, 'Indeterminada', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 298, 'Indeterminada', 2 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 398, 'Indeterminada', 3 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 498, 'Indeterminada', 4 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 598, 'Indeterminada', 5 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 798, 'Indeterminada', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 2098, 'Indeterminada', 20 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 2798, 'Indeterminada', 27 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3098, 'Indeterminada', 30 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3198, 'Indeterminada', 31 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3298, 'Indeterminada', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3398, 'Indeterminada', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3498, 'Indeterminada', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3698, 'Indeterminada', 36 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3998, 'Indeterminada', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4098, 'Indeterminada', 40 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4198, 'Indeterminada', 41 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4398, 'Indeterminada', 43 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4498, 'Indeterminada', 44 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4598, 'Indeterminada', 45 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4698, 'Indeterminada', 46 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4798, 'Indeterminada', 47 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4898, 'Indeterminada', 48 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4998, 'Indeterminada', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5198, 'Indeterminada', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5298, 'Indeterminada', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5398, 'Indeterminada', 53 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5498, 'Indeterminada', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5598, 'Indeterminada', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5698, 'Indeterminada', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5798, 'Indefinida', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5898, 'Indeterminada', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6098, 'Indeterminada', 60 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6198, 'Indeterminada', 61 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6298, 'Indeterminada', 62 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6398, 'Indeterminada', 63 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6498, 'Indeterminada', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6598, 'Indeterminada', 65 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6698, 'Indeterminada', 66 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8198, 'Indeterminada', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8298, 'Indeterminada', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8498, 'Indeterminada', 84 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8698, 'Indeterminada', 86 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9098, 'Indeterminada', 90 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9198, 'Indeterminada', 91 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9298, 'Indeterminada', 92 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9398, 'Indeterminada', 93 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9498, 'Indeterminada', 94 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9598, 'Indeterminada', 95 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 9898, 'Indeterminada', 98 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 21298, 'Indeterminada', 212 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 21398, 'Indeterminada', 213 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 21698, 'Indeterminada', 216 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 21898, 'Indeterminada', 218 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22098, 'Indeterminada', 220 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22198, 'Indeterminada', 221 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22298, 'Indeterminada', 222 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22398, 'Indeterminada', 223 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22498, 'Indeterminada', 224 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22598, 'Indeterminada', 225 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22698, 'Indeterminada', 226 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22798, 'Indeterminada', 227 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 22998, 'Indeterminada', 229 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23098, 'Indeterminada', 230 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23198, 'Indeterminada', 231 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23298, 'Indeterminada', 232 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23398, 'Indeterminada', 233 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23498, 'Indeterminada', 234 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23598, 'Indeterminada', 235 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23698, 'Indeterminada', 236 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23798, 'Indeterminada', 237 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23898, 'Indeterminada', 238 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 23998, 'Indeterminada', 239 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24098, 'Indeterminada', 240 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24198, 'Indeterminada', 241 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24298, 'Indeterminada', 242 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24398, 'Indeterminada', 243 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24498, 'Indeterminada', 244 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24598, 'Indeterminada', 245 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 24998, 'Indeterminada', 249 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25098, 'Indeterminada', 250 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25298, 'Indeterminada', 252 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25498, 'Indeterminada', 254 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25598, 'Indeterminada', 255 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25698, 'Indeterminada', 256 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25798, 'Indeterminada', 257 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 25898, 'Indeterminada', 258 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26098, 'Indeterminada', 260 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26198, 'Indeterminada', 261 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26298, 'Indeterminada', 262 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26398, 'Indeterminada', 263 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26498, 'Indeterminada', 264 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26598, 'Indeterminada', 265 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26698, 'Indeterminada', 266 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26798, 'Indeterminada', 267 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26898, 'Indeterminada', 268 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 26998, 'Indeterminada', 269 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 29098, 'Indeterminada', 290 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 29198, 'Indeterminada', 291 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35198, 'Indeterminada', 351 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35298, 'Indeterminada', 352 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35398, 'Indeterminada', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35498, 'Indeterminada', 354 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35598, 'Indeterminada', 355 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35698, 'Indeterminada', 356 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35798, 'Indeterminada', 357 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35898, 'Indeterminada', 358 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35998, 'Indeterminada', 359 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37098, 'Indeterminada', 370 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37198, 'Indeterminada', 371 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37298, 'Indeterminada', 372 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37398, 'Indeterminada', 373 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37498, 'Indeterminada', 374 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37598, 'Indeterminada', 375 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37698, 'Indeterminada', 376 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37798, 'Indeterminada', 377 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37898, 'Indeterminada', 378 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 37998, 'Indeterminada', 379 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38098, 'Indeterminada', 380 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38198, 'Indeterminada', 381 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38598, 'Indeterminada', 385 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38698, 'Indeterminada', 386 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38798, 'Indeterminada', 387 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38998, 'Indeterminada', 389 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 42098, 'Indeterminada', 420 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 42198, 'Indeterminada', 421 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 42398, 'Indeterminada', 423 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50198, 'Indeterminada', 501 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50298, 'Indeterminada', 502 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50398, 'Indeterminada', 503 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50498, 'Indeterminada', 504 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50598, 'Indeterminada', 505 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50698, 'Indeterminada', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50798, 'Indeterminada', 507 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50998, 'Indeterminada', 509 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59198, 'Indeterminada', 591 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59298, 'Indeterminada', 592 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59398, 'Indeterminada', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59498, 'Indeterminada', 594 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59598, 'Indeterminada', 595 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59698, 'Indeterminada', 596 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59798, 'Indeterminada', 597 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59898, 'Indeterminada', 598 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59998, 'Indeterminada', 599 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67298, 'Indeterminada', 672 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67398, 'Indeterminada', 673 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67498, 'Indeterminada', 674 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67598, 'Indeterminada', 675 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67698, 'Indeterminada', 676 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67798, 'Indeterminada', 677 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67898, 'Indeterminada', 678 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67998, 'Indeterminada', 679 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 68098, 'Indeterminada', 680 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 68598, 'Indeterminada', 685 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 68698, 'Indeterminada', 686 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 68798, 'Indeterminada', 687 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 68898, 'Indeterminada', 688 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 68998, 'Indeterminada', 689 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 69098, 'Indeterminada', 690 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 69198, 'Indeterminada', 691 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 69298, 'Indeterminada', 692 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 85098, 'Indeterminada', 850 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 85398, 'Indeterminada', 853 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 85698, 'Indeterminada', 856 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 88098, 'Indeterminada', 880 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 88698, 'Indeterminada', 886 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96098, 'Indeterminada', 960 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96198, 'Indeterminada', 961 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96298, 'Indeterminada', 962 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96398, 'Indeterminada', 963 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96498, 'Indeterminada', 964 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96598, 'Indeterminada', 965 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96698, 'Indeterminada', 966 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96798, 'Indeterminada', 967 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96898, 'Indeterminada', 968 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97198, 'Indeterminada', 971 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97298, 'Indeterminada', 972 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97398, 'Indeterminada', 973 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97498, 'Indeterminada', 974 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97598, 'Indeterminada', 975 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97698, 'Indeterminada', 976 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 97798, 'Indeterminada', 977 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 99398, 'Indeterminada', 993 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 99498, 'Indeterminada', 994 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 99598, 'Indeterminada', 995 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 99898, 'Indeterminada', 998 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 102, 'Alabama', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 104, 'Alaska', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 105, 'Arizona', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 107, 'Arkansas', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 108, 'California', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 110, 'Colorado', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 111, 'Connecticut', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 113, 'Delaware', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 114, 'Florida', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 116, 'Georgia', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 117, 'Hawaii', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 119, 'Idaho', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 120, 'Illinois', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 122, 'Indiana', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 123, 'Iowa', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 125, 'Kansas', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 126, 'Kentucky', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 128, 'Louisiana', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 129, 'Maine', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 131, 'Maryland', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 132, 'Massachusetts', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 134, 'Michigan', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 135, 'Minnesota', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 137, 'Mississippi', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 138, 'Missouri', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 140, 'Montana', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 141, 'Nebraska', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 143, 'Nevada', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 144, 'New Hampshire', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 146, 'New Jersey', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 147, 'New Mexico', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 149, 'New York', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 150, 'North Carolina', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 152, 'North Dakota', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 153, 'Ohio', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 155, 'Oklahoma', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 156, 'Oregon', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 158, 'Pennsylvania', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 159, 'Rhode Island', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 161, 'South Carolina', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 162, 'South Dakota', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 164, 'Tennessee', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 165, 'Texas', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 167, 'Utah', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 168, 'Vermont', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 170, 'Virginia', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 171, 'Washington', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 173, 'West Virginia', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 174, 'Wisconsin', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 176, 'Wyoming', 1 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3405, 'Andalucía', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3410, 'Aragón', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3415, 'Asturias', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3420, 'Cantabria', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3425, 'Castilla - La Mancha', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3430, 'Castilla - León', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3435, 'Catalunya', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3440, 'Extremadura', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3445, 'Galicia', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3450, 'Islas Baleares', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3455, 'Islas Canarias', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3460, 'La Rioja', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3465, 'Madrid', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3470, 'Murcia', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3475, 'Navarra', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3480, 'País Vasco - Euskadi', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3485, 'Valencia', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3490, 'Ceuta', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3495, 'Melilla', 34 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3904, 'Abruzos', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3908, 'Apulia', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3912, 'Basilicata', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3916, 'Calabria', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3920, 'Campania', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3924, 'Cerdeña', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3928, 'Emilia - Romaña', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3932, 'Friul - Venecia Julia', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3936, 'Las Marcas', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3940, 'Lacio', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3944, 'Liguria', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3948, 'Lombardía', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3952, 'Molise', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3956, 'Piamonte', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3960, 'Sicilia', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3964, 'Toscana', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3968, 'Trentino - Alto Adigio', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3972, 'Umbría', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3976, 'Valle de Aosta', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3980, 'Véneto', 39 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59801, 'Sin Provincias', 598 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59501, 'Sin Provincias', 595 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59304, 'AZUAY', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59308, 'BOLIVAR', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59312, 'CAÑAR', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59316, 'CARCHI', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59320, 'CHIMBORAZO', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59324, 'COTOPAXI', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59328, 'EL ORO', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59332, 'ESMERALDAS', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59336, 'GALAPAGOS', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59340, 'GUAYAS', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59344, 'IMBABURA', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59348, 'LOJA', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59352, 'LOS RIOS', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59356, 'MANABI', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59360, 'MORONA SANTIAGO', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59364, 'NAPO', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59368, 'ORELLANA', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59372, 'PASTAZA', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59376, 'PICHINCHA', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59380, 'SUCUMBIOS', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59384, 'TUNGURAHUA', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59388, 'ZAMORA CHINCHIPE', 593 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 59101, 'Sin Provincias', 591 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50613, 'Alajuela', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50626, 'Cartago', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50639, 'Guanacaste', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50652, 'Heredia', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50665, 'Limón', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50678, 'Puntarenas', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 50691, 'San Jose', 506 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8102, 'Aichi', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8104, 'Akita', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8106, 'Aomori', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8108, 'Chiba', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8110, 'Ehime', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8112, 'Fukui', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8114, 'Fukuoka', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8116, 'Fukushima', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8118, 'Gifu', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8120, 'Gunma', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8122, 'Hiroshima', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8124, 'Hokkaido', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8126, 'Hyogo', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8128, 'Ibaraki', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8130, 'Ishikawa', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8132, 'Iwate', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8134, 'Kagawa', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8136, 'Kagoshima', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8138, 'Kanagawa', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8140, 'Kochi', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8142, 'Kumamoto', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8144, 'Kyoto', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8146, 'Mie', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8148, 'Miyagi', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8150, 'Miyazaki', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8152, 'Nagano', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8154, 'Nagasaki', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8156, 'Nara', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8158, 'Niigata', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8160, 'Oita', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8162, 'Okayama', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8164, 'Okinawa', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8166, 'Osaka', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8168, 'Saga', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8170, 'Saitama', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8172, 'Shiga', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8174, 'Shimane', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8176, 'Shizuoka', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8178, 'Tochigi', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8180, 'Tokushima', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8182, 'Tokio', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8184, 'Tottori', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8186, 'Toyama', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8188, 'Wakayama', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8190, 'Yamagata', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8192, 'Yamaguchi', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8194, 'Yamanashi', 81 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6405, 'Auckland', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6410, 'Bahía de los Halcones', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6415, 'Bahía de Plenty', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6420, 'Canterbury', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6425, 'Costa Oeste', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6430, 'Gisborne', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6435, 'Islas Chatham', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6440, 'Manauatu-Uanganui', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6445, 'Marlborough', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6450, 'Nelson', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6455, 'Otago', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6460, 'Región del Norte', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6465, 'Región del Sur', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6470, 'Taranaki', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6475, 'Tasmania', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6480, 'Waikato', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 6485, 'Wellington', 64 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5803, 'Amazonas', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5806, 'Anzoátegui', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5809, 'Apure', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5812, 'Aragua', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5815, 'Barinas', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5818, 'Bolívar', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5821, 'Carabobo', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5824, 'Cojedes', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5827, 'Delta Amacuro', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5830, 'Dependencias Federales', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5833, 'Distrito Capital', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5836, 'Falcón', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5839, 'Guárico', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5842, 'Lara', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5845, 'Mérida', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5848, 'Miranda', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5851, 'Monagas', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5854, 'Nueva Esparta', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5857, 'Portuguesa', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5860, 'Sucre', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5863, 'Táchira', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5866, 'Trujillo', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5869, 'Vargas', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5872, 'Yaracuy', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5875, 'Zulia', 58 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5703, 'Amazonas', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5706, 'Antioquia', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5709, 'Arauca', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5712, 'Atlántico', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5716, 'Bogotá', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5719, 'Bolívar', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5722, 'Boyacá', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5725, 'Caldas', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5728, 'Caquetá', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5732, 'Casanare', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5735, 'Cauca', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5738, 'César', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5741, 'Chocó', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5744, 'Córdoba', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5748, 'Cundinamarca', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5751, 'Guaviare', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5754, 'Huila', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5757, 'La Guajira', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5760, 'Magdalena', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5764, 'Meta', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5767, 'Nariño', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5770, 'Norte de Santander', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5773, 'Putumayo', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5776, 'Quindió', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5780, 'Risaralda', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5783, 'San Andrés y Providencia', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5786, 'Santander', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5789, 'Sucre', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5792, 'Tolima', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5796, 'Valle del Cauca', 57 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5607, 'AISEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5614, 'ANTOFAGASTA', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5621, 'ARAUCANIA', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5628, 'ATACAMA', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5635, 'BIOBIO', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5642, 'COQUIMBO', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5649, 'LIBERTADOR GENERAL BERNARDO O`HIGGINS', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5656, 'LOS LAGOS', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5663, 'MAGALLANES Y LA ANTARTICA CHILENA', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5670, 'MAULE', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5677, 'METROPOLITANA DE SANTIAGO', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5684, 'TARAPACA', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5691, 'VALPARAISO', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5503, 'Acre', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5506, 'Alagoas', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5509, 'Amapá', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5512, 'Amazonas', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5515, 'Bahia', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5518, 'Ceará', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5521, 'Distrito Federal', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5524, 'Espírito Santo', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5527, 'Goiás', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5530, 'Maranhão', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5533, 'Mato Grosso', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5536, 'Mato Grosso do Sul', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5539, 'Minas Gerais', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5542, 'Pará', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5545, 'Paraíba', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5548, 'Paraná', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5551, 'Pernambuco', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5554, 'Piauí', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5557, 'Rio de Janeiro', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5560, 'Rio Grande do Norte', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5563, 'Rio Grande do Sul', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5566, 'Rondônia', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5569, 'Roraima', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5572, 'Santa Catarina', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5575, 'São Paulo', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5578, 'Sergipe', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5581, 'Tocantins', 55 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5104, 'AMAZONAS', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5108, 'ANCASH', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5112, 'APURIMAC', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5116, 'AREQUIPA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5120, 'AYACUCHO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5124, 'CAJAMARCA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5126, 'CALLAO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5128, 'CUZCO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5132, 'HUANUCO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5136, 'HUANCAVELICA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5140, 'ICA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5144, 'JUNIN', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5148, 'LA LIBERTAD', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5152, 'LAMBAYEQUE', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5156, 'LIMA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5160, 'LORETO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5164, 'MADRE DE DIOS', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5168, 'MOQUEGUA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5172, 'PASCO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5176, 'PIURA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5180, 'PUNO', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5184, 'SAN MARTIN', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5188, 'TACNA', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5192, 'TUMBES', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5196, 'UCAYALI', 51 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4906, 'Baden-Wurtemberg (Baden-Württemberg)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4912, 'Baja Sajonia (Niedersachsen)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4918, 'Baviera', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4924, 'Berlín', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4930, 'Brandeburgo (Brandenburg)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4936, 'Bremen', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4942, 'Hamburgo (Hamburg)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4948, 'Hesse', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4954, 'Mecklemburgo-Pomerania Occidental (Mecklenburg-Vorpommern)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4960, 'Renania del Norte-Westfalia (Nordrhein-Westfalen)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4966, 'Renania-Palatinado (Rheinland-Pfalz)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4972, 'Sajonia (Sachsen)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4975, 'Sajonia-Anhalt (Sachsen-Anhalt)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4978, 'Sarre (Saarland)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4984, 'Schleswig-Holstein', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4990, 'Turingia (Thüringen)', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4101, 'Sin Provincias', 41 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5203, 'Aguascalientes', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5206, 'Baja California Norte', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5209, 'Baja California Sur', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5212, 'Campeche', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5215, 'Chiapas', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5218, 'Chihuahua', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5221, 'Coahuila', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5224, 'Colima', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5227, 'Distrito Federal', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5230, 'Durango', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5233, 'Estado de Mexico', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5236, 'Guanajuato', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5239, 'Guerrero', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5242, 'Hidalgo', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5245, 'Jalisco', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5248, 'Michoacán', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5251, 'Morelos', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5254, 'Nayarit', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5257, 'Nuevo León', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5260, 'Oaxaca', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5263, 'Puebla', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5266, 'Querétaro', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5269, 'Quintana Roo', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5272, 'San Luis Potosí', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5275, 'Sinaloa', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5278, 'Sonora', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5281, 'Tabasco', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5284, 'Tamaulipas', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5287, 'Tlaxcala', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5290, 'Veracruz', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5293, 'Yucatán', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5296, 'Zacatecas', 52 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 124298, 'Indeterminada', 1242 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5494, 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5490, 'Tucumán', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5478, 'Santa Cruz', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5474, 'San Luis', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5470, 'San Juan', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5462, 'Rio Negro', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5458, 'Neuquén', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5454, 'Misiones', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5450, 'Mendoza', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5446, 'La Rioja', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5442, 'La Pampa', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5438, 'Jujuy', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5434, 'Formosa', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5426, 'Chubut', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5418, 'Corrientes', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5410, 'Catamarca', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5486, 'Santiago del Estero', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5482, 'Santa Fe', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5466, 'Salta', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5430, 'Entre Rios', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5422, 'Chaco', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5414, 'Cordoba', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5406, 'Buenos Aires', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 86898, 'Indeterminada', 868 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 999998, 'Indeterminada', 9999 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5402, 'Capital Federal', 54 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 999898, 'Indeterminada', 9998 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 999798, 'Indeterminada', 9997 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 999698, 'Indeterminada', 9996 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 999598, 'Indeterminada', 9995 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 126898, 'Indeterminada', 1268 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 124698, 'Indeterminada', 1246 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 176798, 'Indeterminada', 1767 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 147398, 'Indeterminada', 1473 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 186998, 'Indeterminada', 1869 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 178498, 'Indeterminada', 1784 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 175898, 'Indeterminada', 1758 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 99298, 'Indeterminada', 992 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 7798, 'Indeterminada', 77 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 67098, 'Indeterminada', 670 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 38298, 'Indeterminada', 382 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 701, 'Adiguesia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 702, 'Altai - República', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 703, 'Bashkortostan', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 704, 'Buriatia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 705, 'Carelia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 706, 'Chechenia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 707, 'Chuvasia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 708, 'Daguestán', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 709, 'Ingusetia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 710, 'Jakasia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 711, 'Kabardino-Balkaria', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 712, 'Kalmukia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 713, 'Karacháevo-Cherkesia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 714, 'Komi', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 715, 'Mari El', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 716, 'Mordovia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 717, 'Osetia del Norte - Alania', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 718, 'Saja', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 719, 'Tartaristán', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 720, 'Tuva', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 721, 'Udmurtia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 722, 'Altai - Territorio', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 723, 'Jabarovsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 724, 'Kamchatka', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 725, 'Krasnodar', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 726, 'Krasnoyarsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 727, 'Perm', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 728, 'Primorie', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 729, 'Stavropol', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 730, 'Zabaikalski', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 731, 'Amur', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 732, 'Arkangelsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 733, 'Astrakan', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 734, 'Belgorod', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 735, 'Briansk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 736, 'Cheliabinsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 737, 'Irkutsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 738, 'Ivanovo', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 739, 'Kaliningrado', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 740, 'Kaluga', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 741, 'Kemerovo', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 742, 'Kirov', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 743, 'Kostroma', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 744, 'Kurgan', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 745, 'Kursk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 746, 'Leningrado', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 747, 'Lipetsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 748, 'Magadan', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 749, 'Moscú', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 750, 'Murmansk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 751, 'Nizhni Novgorod', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 752, 'Novgorod', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 753, 'Novosibirsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 754, 'Omsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 755, 'Orel', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 756, 'Oremburgo', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 757, 'Penza', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 758, 'Pskov', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 759, 'Ryazan', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 760, 'Rostov', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 761, 'Sajalin', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 762, 'Samara', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 763, 'Saratov', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 764, 'Smolensk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 765, 'Sverdlovsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 766, 'Tambov', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 767, 'Tiumen', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 768, 'Tomsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 769, 'Tula', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 770, 'Tver', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 771, 'Ulianovsk', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 772, 'Vladimir', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 773, 'Volgogrado', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 774, 'Vologda', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 775, 'Voronezh', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 776, 'Yaroslavl', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 778, 'Provincia Autónoma Hebrea', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 779, 'Chukotka', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 780, 'Janti-Mansi', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 781, 'Nenetsia', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 782, 'Yamalo-Nénets', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 783, 'San Petersburgo', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 784, 'Moscú - Ciudad Autónoma', 7 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3101, 'Zuid-Holland', 31 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3201, 'Amberes', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3204, 'Brabante Flamenco', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3208, 'Brabante Valón', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3212, 'Bruselas', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3216, 'Flandes Oriental', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3220, 'Flandes Occidental', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3224, 'Hainaut', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3228, 'Lieja', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3232, 'Limburgo', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3236, 'Luxemburgo', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3240, 'Namur', 32 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3301, 'Alsacia', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3305, 'Alta Normandía', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3309, 'Aquitania', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3313, 'Auvernia', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3317, 'Borgoña', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3321, 'Bretaña', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3325, 'Centro', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3329, 'Champaña-Ardenas', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3333, 'Córcega', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3337, 'Franco Condado', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3341, 'Isla de Francia', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3345, 'Limousin', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3349, 'Languedoc-Rosellón', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3353, 'Lorena', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3357, 'Mediodía-Pirineos', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3361, 'Norte-Paso de Calais', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3367, 'Baja Normandía', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3371, 'País del Loira', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3373, 'Picardía', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3375, 'Poitou-Charente', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3379, 'Provenza-Alpes-Costa Azul', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3383, 'Ródano-Alpes', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3387, 'Guadalupe', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3391, 'Martinica', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3395, 'Guayana', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 3399, 'Reunión', 33 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4401, 'Londres', 44 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 4956, 'Nordheim Westfallen', 49 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5625, 'ARICA Y PARINACOTA', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 5653, 'LOS RIOS', 56 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8209, 'Seúl (Ciudad Capital)', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8218, 'Gyeonggi', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8227, 'Gangwon', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8236, 'Chungcheong del Norte', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8245, 'Chungcheong del Sur', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8254, 'Jeolla del Norte', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8263, 'Jeolla del Sur', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8272, 'Gyeongsang del Norte', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8281, 'Gyeongsang del Sur', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 8290, 'Jeju', 82 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35303, 'Carlow', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35306, 'Cavan', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35309, 'Clare', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35315, 'Donegal', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35318, 'Dublin', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35321, 'Galway', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35324, 'Kerry', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35327, 'Kildare', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35330, 'Kilkenny', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35333, 'Laois', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35336, 'Leitrim', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35339, 'Limerick', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35342, 'Longford', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35345, 'Louth', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35348, 'Mayo', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35351, 'Meath', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35354, 'Monaghan', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35357, 'Offaly', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35360, 'Roscommon', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35363, 'Sligo', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35369, 'Waterford', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35372, 'Westmeath', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35375, 'Wexford', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35378, 'Wicklow', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35366, 'North Tipperary', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35368, 'South Tipperary', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 35312, 'Cork', 353 );
INSERT INTO mug_provincias (provincia, nombre, pais) VALUES ( 96601, 'Riyadh', 966 );
